linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - gofmt
    - misspell
  disable:
    - funlen
    - cyclop
    - gocognit

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
